"""
scheduler.py

Agent 2: Scheduling Engine

This script reads:
1. data/employees.csv
2. outputs/forecast.json

It uses Google OR-Tools to generate a workforce schedule based on:
- forecasted staffing demand
- employee availability
- employee skills
- maximum weekly hours
- hourly rate

Outputs:
1. outputs/schedule.csv
2. outputs/schedule.json
3. outputs/schedule_summary.json

Project role:
This script represents the optimization tool used by Agent 2
(Scheduling & Explanation Agent).
"""


# Imports

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Tuple

import pandas as pd
from ortools.sat.python import cp_model


# Configuration

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

EMPLOYEE_FILE = DATA_DIR / "employees.csv"
FORECAST_FILE = OUTPUTS_DIR / "forecast.json"

SCHEDULE_CSV_FILE = OUTPUTS_DIR / "schedule.csv"
SCHEDULE_JSON_FILE = OUTPUTS_DIR / "schedule.json"
SUMMARY_JSON_FILE = OUTPUTS_DIR / "schedule_summary.json"

SHIFT_HOURS = 8
DAYS_TO_SCHEDULE = 3

# Penalty weights.
# Higher uncovered penalty means the solver prioritizes covering demand.
UNCOVERED_DEMAND_PENALTY = 1000

# Hourly cost is included with a smaller weight.
COST_WEIGHT = 1


# Data loading functions

def ensure_output_folder() -> None:
    """Create outputs folder if it does not exist."""
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)


def load_employees() -> pd.DataFrame:
    """Load employee data."""
    if not EMPLOYEE_FILE.exists():
        raise FileNotFoundError(
            f"Could not find {EMPLOYEE_FILE}. "
            "Run python src/generate_data.py first."
        )

    employees_df = pd.read_csv(EMPLOYEE_FILE)

    # Use only active employees for scheduling.
    employees_df = employees_df[employees_df["status"] == "Active"].copy()
    employees_df = employees_df.reset_index(drop=True)

    return employees_df


def load_forecast() -> pd.DataFrame:
    """Load forecast data generated by Agent 1."""
    if not FORECAST_FILE.exists():
        raise FileNotFoundError(
            f"Could not find {FORECAST_FILE}. "
            "Run python src/forecast_model.py first."
        )

    forecast_df = pd.read_json(FORECAST_FILE)
    forecast_df["date"] = pd.to_datetime(forecast_df["date"])

    # Use only the first N forecast days for Version 1.
    selected_dates = sorted(forecast_df["date"].unique())[:DAYS_TO_SCHEDULE]
    forecast_df = forecast_df[forecast_df["date"].isin(selected_dates)].copy()

    forecast_df = forecast_df.sort_values(
        ["date", "shift", "skill_required"]
    ).reset_index(drop=True)

    return forecast_df


# Helper functions

def parse_csv_list(value: str) -> List[str]:
    """Parse comma-separated values from employee fields."""
    if pd.isna(value):
        return []
    return [item.strip() for item in str(value).split(",") if item.strip()]


def employee_available_for_day(employee_row: pd.Series, day_short: str) -> bool:
    """Check if employee is available on a given day."""
    available_days = parse_csv_list(employee_row["available_days"])
    return day_short in available_days


def employee_available_for_shift(employee_row: pd.Series, shift: str) -> bool:
    """Check if employee is available for a given shift."""
    available_shifts = parse_csv_list(employee_row["available_shifts"])
    return shift in available_shifts


def employee_has_skill(employee_row: pd.Series, required_skill: str) -> bool:
    """Check if employee has the required skill as primary or secondary."""
    primary_skill = str(employee_row["primary_skill"]).strip()
    secondary_skill = str(employee_row["secondary_skill"]).strip()

    return required_skill in [primary_skill, secondary_skill]


def get_day_short(date_value: pd.Timestamp) -> str:
    """Convert date to short weekday format used in employee availability."""
    mapping = {
        "Monday": "Mon",
        "Tuesday": "Tue",
        "Wednesday": "Wed",
        "Thursday": "Thu",
        "Friday": "Fri",
        "Saturday": "Sat",
        "Sunday": "Sun",
    }
    return mapping[date_value.strftime("%A")]


def build_shift_requirements(forecast_df: pd.DataFrame) -> List[Dict]:
    """
    Convert forecast rows into scheduling requirements.

    Each requirement means:
    On this date, shift, and skill, assign N employees.
    """
    requirements = []

    for _, row in forecast_df.iterrows():
        date_value = row["date"]
        requirements.append({
            "date": date_value.strftime("%Y-%m-%d"),
            "day_of_week": date_value.strftime("%A"),
            "day_short": get_day_short(date_value),
            "shift": row["shift"],
            "skill_required": row["skill_required"],
            "required_staff": int(row["forecast_required_staff"]),
        })

    return requirements


# OR-Tools scheduling model

def solve_schedule(
    employees_df: pd.DataFrame,
    requirements: List[Dict]
) -> Tuple[pd.DataFrame, Dict]:
    """
    Build and solve the scheduling optimization model.

    Decision variable:
    assign[e, r] = 1 if employee e is assigned to requirement r.

    We also create uncovered[r] variables to allow unmet demand when
    there are not enough qualified or available employees.
    """
    model = cp_model.CpModel()

    employee_indices = list(range(len(employees_df)))
    requirement_indices = list(range(len(requirements)))

    # Decision variables.
    assign = {}
    for e in employee_indices:
        for r in requirement_indices:
            assign[(e, r)] = model.NewBoolVar(f"assign_e{e}_r{r}")

    # Uncovered demand variables.
    uncovered = {}
    for r in requirement_indices:
        required_staff = requirements[r]["required_staff"]
        uncovered[r] = model.NewIntVar(
            0,
            required_staff,
            f"uncovered_r{r}"
        )


    # Constraint 1:
    # Employee can only be assigned if available and qualified.
    for e in employee_indices:
        employee = employees_df.iloc[e]

        for r in requirement_indices:
            req = requirements[r]

            is_available_day = employee_available_for_day(employee, req["day_short"])
            is_available_shift = employee_available_for_shift(employee, req["shift"])
            has_skill = employee_has_skill(employee, req["skill_required"])

            if not (is_available_day and is_available_shift and has_skill):
                model.Add(assign[(e, r)] == 0)

    # Constraint 2:
    # Coverage constraint with uncovered demand allowed.
    for r in requirement_indices:
        required_staff = requirements[r]["required_staff"]

        model.Add(
            sum(assign[(e, r)] for e in employee_indices) + uncovered[r] == required_staff
        )

    # Constraint 3:
    # An employee cannot be assigned to two skill requirements in the same date and shift.
    date_shift_to_requirements: Dict[Tuple[str, str], List[int]] = {}

    for r, req in enumerate(requirements):
        key = (req["date"], req["shift"])
        date_shift_to_requirements.setdefault(key, []).append(r)

    for e in employee_indices:
        for _, req_indices in date_shift_to_requirements.items():
            model.Add(
                sum(assign[(e, r)] for r in req_indices) <= 1
            )

    # Constraint 4:
    # Max weekly hours per employee.
    for e in employee_indices:
        max_hours = int(employees_df.iloc[e]["max_hours_per_week"])
        max_shifts = max_hours // SHIFT_HOURS

        model.Add(
            sum(assign[(e, r)] for r in requirement_indices) <= max_shifts
        )

    # Objective:
    # Minimize uncovered demand first, then labor cost.
    objective_terms = []

    for r in requirement_indices:
        objective_terms.append(UNCOVERED_DEMAND_PENALTY * uncovered[r])

    for e in employee_indices:
        hourly_rate = float(employees_df.iloc[e]["hourly_rate"])
        shift_cost = int(round(hourly_rate * SHIFT_HOURS))

        for r in requirement_indices:
            objective_terms.append(COST_WEIGHT * shift_cost * assign[(e, r)])

    model.Minimize(sum(objective_terms))

    # Solve.
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = 30
    solver.parameters.num_search_workers = 8

    status = solver.Solve(model)

    if status not in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
        raise RuntimeError("No feasible schedule found.")

    # Build schedule output.
    schedule_rows = []
    total_required = 0
    total_assigned = 0
    total_uncovered = 0
    total_labor_cost = 0.0

    for r in requirement_indices:
        req = requirements[r]
        required_staff = req["required_staff"]
        uncovered_staff = solver.Value(uncovered[r])
        assigned_count = required_staff - uncovered_staff

        total_required += required_staff
        total_assigned += assigned_count
        total_uncovered += uncovered_staff

        for e in employee_indices:
            if solver.Value(assign[(e, r)]) == 1:
                employee = employees_df.iloc[e]
                shift_cost = float(employee["hourly_rate"]) * SHIFT_HOURS
                total_labor_cost += shift_cost

                schedule_rows.append({
                    "date": req["date"],
                    "day_of_week": req["day_of_week"],
                    "shift": req["shift"],
                    "skill_required": req["skill_required"],
                    "employee_id": employee["employee_id"],
                    "employee_name": employee["name"],
                    "primary_skill": employee["primary_skill"],
                    "secondary_skill": employee["secondary_skill"],
                    "hourly_rate": float(employee["hourly_rate"]),
                    "shift_hours": SHIFT_HOURS,
                    "shift_cost": round(shift_cost, 2),
                    "assignment_status": "Assigned",
                })

        # Add uncovered rows for transparency.
        if uncovered_staff > 0:
            for i in range(uncovered_staff):
                schedule_rows.append({
                    "date": req["date"],
                    "day_of_week": req["day_of_week"],
                    "shift": req["shift"],
                    "skill_required": req["skill_required"],
                    "employee_id": None,
                    "employee_name": "UNFILLED",
                    "primary_skill": None,
                    "secondary_skill": None,
                    "hourly_rate": None,
                    "shift_hours": None,
                    "shift_cost": None,
                    "assignment_status": "Unfilled",
                })

    schedule_df = pd.DataFrame(schedule_rows)


    summary = {
        "solver_status": solver.StatusName(status),
        "days_scheduled": DAYS_TO_SCHEDULE,
        "total_required_positions": int(total_required),
        "total_assigned_positions": int(total_assigned),
        "total_unfilled_positions": int(total_uncovered),
        "coverage_rate": round(total_assigned / total_required, 4) if total_required else 0,
        "estimated_labor_cost": round(total_labor_cost, 2),
    }

    return schedule_df, summary


# Save outputs

def save_schedule(schedule_df: pd.DataFrame, summary: Dict) -> None:
    """Save schedule and summary files."""
    schedule_df.to_csv(SCHEDULE_CSV_FILE, index=False)

    records = schedule_df.to_dict(orient="records")

    with open(SCHEDULE_JSON_FILE, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)

    with open(SUMMARY_JSON_FILE, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)


# Main function

def main() -> None:
    """Run the scheduling engine."""
    ensure_output_folder()

    print("Loading employee data...")
    employees_df = load_employees()
    print(f"Active employees loaded: {len(employees_df)}")

    print("\nLoading forecast data...")
    forecast_df = load_forecast()
    print(f"Forecast rows loaded for scheduling: {len(forecast_df)}")
    print(f"Days to schedule: {DAYS_TO_SCHEDULE}")

    print("\nBuilding shift requirements...")
    requirements = build_shift_requirements(forecast_df)
    total_required = sum(req["required_staff"] for req in requirements)
    print(f"Scheduling requirements: {len(requirements)}")
    print(f"Total required positions: {total_required}")

    print("\nSolving schedule with OR-Tools...")
    schedule_df, summary = solve_schedule(employees_df, requirements)

    save_schedule(schedule_df, summary)

    print("\nSchedule generated successfully.")
    print(f"Schedule CSV: {SCHEDULE_CSV_FILE}")
    print(f"Schedule JSON: {SCHEDULE_JSON_FILE}")
    print(f"Summary JSON: {SUMMARY_JSON_FILE}")

    print("\nSchedule summary:")
    for key, value in summary.items():
        print(f"- {key}: {value}")

    print("\nSchedule sample:")
    print(schedule_df.head(20).to_string(index=False))


if __name__ == "__main__":
    main()
